server:
  port: 8002

spring:
  datasource:
#    url: jdbc:mysql://uspresidential.cvd6syoq3dtp.us-west-1.rds.amazonaws.com:3306
    url: jdbc:mysql://${RDS_HOSTNAME}:3306/uspresidential
#    url: jdbc:mysql://192.168.2.235:3306
    username: lucjross
    password: password
    platform: mysql
    test-on-borrow: true
    validation-query: select 1
    separator: \n;\n
    continue-on-error: true

debug: true
#logging.level.org.springframework.security=DEBUG